- name: PITR directories are present
  file:
    path: "/var/lib/postgresql/{{ db.version }}/{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  become_user: postgres
  loop:
    - wals
    - backups

- name: Archiving is configured
  lineinfile:
    path: "/etc/postgresql/{{ db.version }}/{{ db.cluster_name }}/postgresql.conf"
    line: "{{ item }}"
  loop:
    - 'wal_level=archive'
    - 'archive_mode=on'
    - "archive_command = 'test ! -f /var/lib/postgresql/{{ db.version }}/wals/%f && cp %p /var/lib/postgresql/{{ db.version }}/wals/%f'"
  notify:
    - PostgreSQL Restarted
  become_user: postgres
