<% require_relative 'lib/pitr/config' %>
name: <%= File.basename(Dir.pwd) %>

on_project_first_start: scripts/setup
on_project_start: vagrant up
on_project_stop: vagrant halt

windows:
  - test:
      panes:
        - ginkgo watch
        -
  - vm:
      panes:
        - "fswatch -r ansible/**/* | xargs -I {} vagrant provision"
        - vagrant ssh
  - db:
      panes:
        - "psql <%= PITR::Config::DB.new('config.yml').url %>"
