<% require_relative 'lib/pitr/config' %>
name: <%= File.basename(Dir.pwd) %>

on_project_start: vagrant up
on_project_stop: vagrant halt

windows:
  - test:
      layout: tiled
      panes:
        - ginkgo watch -v -r
        - vagrant ssh -c 'sudo -u postgres tail -f /var/log/postgresql/postgresql-11-main.log'
        - 
  - vm:
      panes:
        - "fswatch -r ansible/**/* | xargs -I {} vagrant provision"
        - vagrant ssh
  - db:
      panes:
        - "psql <%= PITR::Config::DB.new('config.yml').url %>"
