<%
  require 'shellwords'
  require_relative 'lib/pitr/config'
  master = PITR::Config::DB.new('config.yml', 'master')
%>

name: <%= File.basename(Dir.pwd) %>

on_project_start: vagrant up --provision
on_project_stop: vagrant halt

windows:
  - tests:
      layout: tiled
      panes:
        - bin/ginkgo -v -r; bin/ginkgo watch -v -r
        - vagrant ssh master -c 'sudo -u postgres tail -f /var/log/postgresql/postgresql-<%= db.version %>-main.log'
        -

  - master:
      panes:
        - psql <%= Shellwords.escape(db.local_url) %>
        - vagrant ssh master

  - minio:
      panes:
        - vagrant ssh minio -c 'sudo -u minio tail -f /var/log/minio.log'
        - vagrant ssh minio

  - deployment:
      panes:
        - scripts/watch
        -
