<% require_relative 'lib/pitr/config' %>
name: <%= File.basename(Dir.pwd) %>

on_project_first_start: >-
  go get
  github.com/onsi/ginkgo/ginkgo
  github.com/onsi/gomega
  github.com/lib/pq
  gopkg.in/yaml.v2
  github.com/mikkeloscar/sshconfig
on_project_start: vagrant up
on_project_stop: vagrant halt

windows:
  - test:
      panes:
        - ginkgo watch
        -
  - vm:
      panes:
        - "fswatch -r ansible/**/*.yml | xargs -I {} vagrant provision"
        - vagrant ssh
  - db:
      panes:
        - "psql <%= PITR::Config::DB.new('config.yml').url %>"
