<%
  require 'shellwords'
  require_relative 'lib/pitr/config'
  master = PITR::Config::DB.new('config.yml', 'master')
  standby = PITR::Config::DB.new(Pathname(__dir__) / 'config.yml', 'standby')
%>

name: <%= File.basename(Dir.pwd) %>

on_project_start: vagrant up --provision
on_project_stop: vagrant halt

windows:
  - tests:
      layout: tiled
      panes:
        - vagrant ssh master -c 'sudo -u postgres tail -f /var/log/postgresql/postgresql-<%= master.version %>-main.log'
        - vagrant ssh standby -c 'sudo -u postgres tail -f /var/log/postgresql/postgresql-<%= master.version %>-main.log'
        - bin/ginkgo -v -r; bin/ginkgo watch -v -r

  - master:
      panes:
        - psql <%= Shellwords.escape(master.url) %>
        - vagrant ssh master

  - standby:
      panes:
        - psql <%= Shellwords.escape(standby.url) %>
        - vagrant ssh standby

  - minio:
      panes:
        - vagrant ssh minio -c 'sudo -u minio tail -f /var/log/minio.log'
        - vagrant ssh minio

  - deployment:
      panes:
        - scripts/watch
        -
