db:
  host: 192.168.71.10
  version: '11'
  cluster_name: main
  local_port: 15432
  name: sandbox
  user: foobar
  password: "9Gp0efB5VYBdeOu-TnbTb5VqjnsLFXw7rUV55SidDk8"
  # Params are optional:
  # params:
  #   sslmode: verify-full
  #   connect_timeout: 10

pgbackrest:
  stanza: pitr

minio:
  host: 192.168.71.20
  local_port: 18443
  access_key: "-5AV_l3QpgKTxqTBaIvtTHxL8BM4Hadm6T1bSpWeL9g"
  secret_key: "mJ5e-3GMUPnSaGYSlHzTmxL01Qu20ZtZdMrP8u4H9Fc"
