db:
  host: 192.168.71.10
  version: '11'
  cluster_name: main
  local_port: 15432
  name: sandbox
  user: foobar
  password: "9Gp0efB5VYBdeOu-TnbTb5VqjnsLFXw7rUV55SidDk8"
  # Params are optional:
  # params:
  #   sslmode: verify-full
  #   connect_timeout: 10

pgbackrest:
  stanza: pitr
  archive_type: local # local, s3 or minio; default: local
  s3_bucket: postgres-pitr # only used for s3 or minio
