master: &master
  host: 192.168.71.10
  version: '11'
  cluster_name: main
  local_port: 15432
  name: sandbox
  user: foobar
  password: "9Gp0efB5VYBdeOu-TnbTb5VqjnsLFXw7rUV55SidDk8"
  # Params are optional:
  # params:
  #   sslmode: verify-full
  #   connect_timeout: 10

pgbackrest:
  stanza: pitr
  archive_type: minio # local, s3 or minio; default: local
  s3_bucket: postgres-backup # only used for s3 or minio

  # If present, encryption is configured according to
  # https://pgbackrest.org/user-guide.html#quickstart/configure-encryption
  cipher_pass: "FNqDM9S6zbroiFY50Y94uNPYgOYXRvkE6RA/jmoPxj3wbn9wWNhUSahQ0nlf9ItH"

minio:
  domain: minio.local
  host: 192.168.71.20
  local_port: 18443
  access_key: "5AVl3QpgKTxqTBaIvtTHxL8BM4Hadm6T1bSpWeL9gX"
  secret_key: "mJ5e3GMUPnSaGYSlHzTmxL01Qu20ZtZdMrP8u4H9Fc"

standby:
  <<: *master
  host: 192.168.71.30
  local_port: 16432
