- name: Repo key is available
  apt_key:
    url: https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
    state: present

- name: Repository is present
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'
    state: present
    filename: pgdg
    update_cache: true

- name: Program is installed
  apt:
    name:
      - "postgresql-{{ master.version }}"
      - "postgresql-contrib-{{ master.version }}"
      - libpq-dev
      - python3-psycopg2
    state: present

- name: Server is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Database exists
  postgresql_db:
    name: "{{ master.name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
  become_user: postgres

- name: User has access to the database
  postgresql_user:
    db: "{{ master.name }}"
    name: "{{ master.user }}"
    password: "{{ master.password }}"
    priv: ALL
    state: present
  become_user: postgres

- name: User does not have unnecessary privileges
  postgresql_user:
    name: "{{ master.user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  become_user: postgres

- name: Allow authenticated connections from 10.0.0.0
  lineinfile:
    path: "/etc/postgresql/{{ master.version }}/{{ master.cluster_name }}/pg_hba.conf"
    regexp: '^host all all 192.168.0.0'
    line: "host all all 192.168.0.0/16 md5"
  notify:
    - PostgreSQL Restarted
  become_user: postgres

- name: Listen on all interfaces
  lineinfile:
    path: "/etc/postgresql/{{ master.version }}/{{ master.cluster_name }}/postgresql.conf"
    regexp: '^listen_addresses'
    line: "listen_addresses = '*'"
  notify:
    - PostgreSQL Restarted
  become_user: postgres

- name: Log all SQL statements
  lineinfile:
    path: "/etc/postgresql/{{ master.version }}/{{ master.cluster_name }}/postgresql.conf"
    regexp: '^log_statement'
    line: "log_statement = 'all'"
  notify:
    - PostgreSQL Restarted
  become_user: postgres
