- name: Binary is present
  get_url:
    url: "https://dl.minio.io/client/mc/release/linux-amd64/mc"
    dest: "/usr/local/bin/mc"
    mode: "0755"
  become: true

- name: Python PIP is installed
  apt:
    name: python3-pip
    state: present

- name: Ansible module requirements are satisfied
  pip:
    name: boto3

- name: "Include tasks for backup manager {{ master.backup_manager }}"
  include_tasks: "{{ master.backup_manager }}.yml"
