- name: Fetch binary
  unarchive:
    src: https://github.com/wal-g/wal-g/releases/download/v0.2.3/wal-g.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Profile is set
  template:
    src: profile.j2
    dest: ~/.profile
  become_user: postgres

- name: Archiving is configured
  lineinfile:
    path: "/etc/postgresql/{{ master.version }}/{{ master.cluster_name }}/postgresql.conf"
    line: "{{ item }}"
  loop:
    - 'wal_level = hot_standby'
    - 'max_wal_senders = 3'
    - 'archive_mode = on'
    - "archive_command = 'bash --login -c \"wal-g wal-push %p\"'"
  notify:
    - PostgreSQL Restarted
  become_user: postgres
