#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

echo "Installing brew dependencies (may ask for your sudo password):"
brew bundle

echo Installing gem dependencies:
gem install tmuxinator

echo Installing go dependencies:
go get \
  github.com/onsi/ginkgo/ginkgo \
  github.com/onsi/gomega \
  github.com/lib/pq \
  gopkg.in/yaml.v2 \
  github.com/mikkeloscar/sshconfig

echo Done.