- hosts: databases
  become: true

  vars_files:
    - ../config.yml

  roles:
    - common
    - postgres
    - pgbackrest

- hosts: blobstores
  become: true

  vars_files:
    - ../config.yml

  roles:
    - common
    - minio
