- hosts: db-masters
  become: true
  vars_files:
    - ../config.yml
  roles:
    - common
    - postgres
    - minio-client
    - pgbackrest-master

- hosts: db-standbys
  become: true
  vars_files:
    - ../config.yml
  roles:
    - common
    - postgres
    - minio-client
    - pgbackrest-standby

- hosts: blobstores
  become: true
  vars_files:
    - ../config.yml
  roles:
    - common
    - minio
