- hosts: db-masters
  become: true
  vars_files:
    - ../config.yml
  roles:
    - common
    - postgres
    - minio-client
    - pgbackrest-master

  roles:
    - common
    - postgres
    - pgbackrest
    - minio-client

- hosts: blobstores
  become: true

  vars_files:
    - ../config.yml

  roles:
    - common
    - minio
