- name: Binary is present
  get_url:
    url: "https://dl.minio.io/server/minio/release/linux-amd64/minio"
    dest: "/usr/local/bin/minio"
    mode: "0755"
  become: true

- name: System group exists
  group:
    name: minio
    state: present
  become: true

- name: System user exists
  user:
    name: minio
    group: minio
    system: true
    createhome: true
    home: /var/lib/minio
    shell: /bin/false
  become: true

- name: Log file exists, with the right permissions
  file:
    path: /var/log/minio.log
    state: touch
    owner: minio
    group: minio
  become: true

- name: Service definition file is up-to-date
  template:
    src: minio.service.j2
    dest: /lib/systemd/system/minio.service
  notify:
    - Minio Restarted
  become: true

- name: TLS is configured
  include_tasks: tls.yml
  when: minio.use_ssl

- name: Minio can bind to to privileged ports
  capabilities:
    path: /usr/local/bin/minio
    capability: cap_net_bind_service+ep
    state: present
  become: true

- name: Service is running and enabled at boot
  service:
    name: minio
    state: started
    enabled: yes
