- name: Directory for private keys exists
  file:
    path: /var/lib/minio/.minio/certs
    state: directory
    owner: minio
    group: minio
  become: true

- name: Private key for SSL cert exists
  openssl_privatekey:
    path: /var/lib/minio/.minio/certs/private.key
    owner: minio
    group: minio
  become: true

- name: Certificate signing request exists
  openssl_csr:
    path: /var/lib/minio/.minio/certs/public.csr
    privatekey_path: /var/lib/minio/.minio/certs/private.key
    common_name: "{{ minio.host }}"
    owner: minio
    group: minio
  become: true

- name: Self Signed OpenSSL certificate exists
  openssl_certificate:
    path: /var/lib/minio/.minio/certs/public.crt
    privatekey_path: /var/lib/minio/.minio/certs/private.key
    csr_path: /var/lib/minio/.minio/certs/public.csr
    provider: selfsigned
    owner: minio
    group: minio
  become: true
